### ISSUE TITLE
Unable to transform sensor_msgs/PointCloud2 from /base_laser_link frame to /odom frame

### ISSUE THREAD

**Issue by ashwin-kumat** [lucasw/transform_point_cloud#5]
I am using rosbag data from MIT Stata Center Data Set and I want to transform sensor_msgs/PointCloud2 from /base_laser_link frame to /odom frame. No msg being published at /point_cloud_transformed topic. I have made the necessary changes in subscriber node.

As I am using rosbag file, I have used param name="use_sim_time" value="true" in my launch file.

After waiting for 2-3 min, following error shows up-

Warning: TF_OLD_DATA ignoring data from the past for frame r_upper_arm_roll_link at time 1.29588e+09 according to authority /play_1584757549814704892
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
Warning: TF_OLD_DATA ignoring data from the past for frame r_wrist_flex_link at time 1.29588e+09 according to authority /play_1584757549814704892
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
Warning: TF_OLD_DATA ignoring data from the past for frame r_wrist_roll_link at time 1.29588e+09 according to authority /play_1584757549814704892
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
Warning: TF_OLD_DATA ignoring data from the past for frame sensor_mount_link at time 1.29588e+09 according to authority /play_1584757549814704892
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
Warning: TF_OLD_DATA ignoring data from the past for frame torso_lift_link at time 1.29588e+09 according to authority /play_1584757549814704892
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
Warning: TF_OLD_DATA ignoring data from the past for frame wide_stereo_gazebo_l_stereo_camera_frame at time 1.29588e+09 according to authority /play_1584757549814704892
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
Warning: TF_OLD_DATA ignoring data from the past for frame wide_stereo_gazebo_l_stereo_camera_optical_frame at time 1.29588e+09 according to authority /play_1584757549814704892
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
Warning: TF_OLD_DATA ignoring data from the past for frame wide_stereo_gazebo_r_stereo_camera_frame at time 1.29588e+09 according to authority /play_1584757549814704892
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
Warning: TF_OLD_DATA ignoring data from the past for frame wide_stereo_gazebo_r_stereo_camera_optical_frame at time 1.29588e+09 according to authority /play_1584757549814704892
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
Warning: TF_OLD_DATA ignoring data from the past for frame wide_stereo_link at time 1.29588e+09 according to authority /play_1584757549814704892
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
Warning: TF_OLD_DATA ignoring data from the past for frame wide_stereo_optical_frame at time 1.29588e+09 according to authority /play_1584757549814704892
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-kinetic-tf2-0.5.20/src/buffer_core.cpp
.......

Kindly help.

**Comment by lucasw** [comment]
Are you also using --clock with your rosbag play?

**Comment by ashwin-kumat** [comment]
Using --clock worked for me. Thank you so much for helping and for creating this library.
